/**
 * Asset generation spec for the open world.
 * Assets are sorted by priority (lower = generated first).
 * The pipeline generates in order and stops when Tripo balance <= 100.
 *
 * Credit budget: ~21110 (starting 21210, leave <=100 buffer).
 * high spec ~70 credits, standard ~20 credits.
 */
import type { AssetRequest } from './types.js';

function req(
  id: string,
  category: AssetRequest['category'],
  name: string,
  prompt: string,
  spec: AssetRequest['spec'],
  targetHeight: number,
  priority: number,
  tags?: string[],
): AssetRequest {
  return { id, category, name, prompt, spec, targetHeight, priority, tags };
}

// ─── 1. Six landmark buildings (highest priority, high spec) ────────────────
const buildings: AssetRequest[] = [
  req('building-court', 'buildings', '法庭',
    'A grand neoclassical courthouse building with tall marble columns, triangular pediment, grand staircase entrance, stone facade, symmetrical design, game-ready 3D model, clean topology',
    'high', 12, 0, ['landmark', 'enterable']),
  req('building-talkshow', 'buildings', '脱口秀剧场',
    'A modern comedy club theater building with neon signage, marquee lights, glass entrance, brick facade, art deco details, game-ready 3D model',
    'high', 10, 0, ['landmark', 'enterable']),
  req('building-werewolf', 'buildings', '狼人杀哥特公馆',
    'A gothic Victorian mansion with pointed arches, stained glass windows, dark stone, towers, iron gates, mysterious atmosphere, game-ready 3D model',
    'high', 14, 0, ['landmark', 'enterable']),
  req('building-bar', 'buildings', '酒吧',
    'A stylish modern bar and lounge building with warm lighting, large windows, outdoor seating, wooden accents, neon sign, game-ready 3D model',
    'high', 8, 0, ['landmark', 'enterable']),
  req('building-gym', 'buildings', '健身房',
    'A modern fitness center building with glass walls, industrial style, large entrance, sports branding, clean lines, game-ready 3D model',
    'high', 9, 0, ['landmark', 'enterable']),
  req('building-library', 'buildings', '图书馆',
    'A grand classical library building with arched windows, brick and stone, clock on facade, steps leading to entrance, scholarly atmosphere, game-ready 3D model',
    'high', 11, 0, ['landmark', 'enterable']),
];

// ─── 2. City infrastructure ─────────────────────────────────────────────────
const cityInfra: AssetRequest[] = [
  req('city-gate-main', 'buildings', '主城门',
    'A massive medieval city gate with two towers, arched passage, stone walls, wooden doors, battlements, game-ready 3D model',
    'high', 15, 1, ['wall']),
  req('city-wall-segment', 'buildings', '城墙段',
    'A straight segment of medieval stone city wall with battlements on top, sturdy and weathered, game-ready 3D model',
    'high', 6, 1, ['wall', 'repeatable']),
  req('city-wall-curve', 'buildings', '弧形城墙',
    'A curved corner segment of medieval stone city wall with crenellations, game-ready 3D model',
    'high', 6, 1, ['wall', 'repeatable']),
  req('city-guard-tower', 'buildings', '岗楼',
    'A square stone guard tower with crenellated top, arrow slits, wooden door, game-ready 3D model',
    'high', 10, 1, ['wall']),
  req('city-bridge-stone', 'buildings', '石桥',
    'An arched stone bridge with railings, weathered texture, spans a waterway, game-ready 3D model',
    'high', 5, 1, ['path']),
  req('city-bridge-wooden', 'buildings', '木桥',
    'A rustic wooden bridge with plank deck and rope railings, game-ready 3D model',
    'standard', 3, 2, ['path']),
  req('city-archway', 'buildings', '拱门',
    'A decorative stone archway monument with carvings, freestanding, game-ready 3D model',
    'high', 8, 1, ['plaza']),
  req('city-clock-tower', 'buildings', '钟楼',
    'A tall clock tower with bell chamber, clock faces on all sides, pointed roof, stone construction, game-ready 3D model',
    'high', 18, 1, ['landmark']),
  req('city-watchtower', 'buildings', '瞭望塔',
    'A tall cylindrical watchtower with conical roof, windows, stone base, game-ready 3D model',
    'high', 14, 2, ['wall']),
  req('city-fountain-grand', 'plaza', '大喷泉',
    'A grand multi-tiered fountain with central statue, water basin, stone carvings, ornate design, game-ready 3D model',
    'high', 6, 1, ['plaza', 'water']),
  req('city-statue-hero', 'plaza', '英雄雕像',
    'A heroic statue of a standing figure on a marble pedestal, bronze material, dramatic pose, game-ready 3D model',
    'high', 5, 1, ['plaza']),
  req('city-pavilion', 'buildings', '凉亭',
    'A traditional hexagonal pavilion with curved roof, wooden pillars, stone base, game-ready 3D model',
    'high', 5, 2, ['plaza']),
];

// ─── 3. Plaza features ──────────────────────────────────────────────────────
const plazaFeatures: AssetRequest[] = [
  req('plaza-stage', 'plaza', '舞台',
    'A raised outdoor performance stage with wooden floor, backdrop frame, steps, game-ready 3D model',
    'high', 3, 2, ['plaza']),
  req('plaza-stall-food', 'plaza', '小吃摊',
    'A colorful food stall cart with awning, counter, hanging lanterns, display shelves, game-ready 3D model',
    'high', 3, 2, ['plaza', 'repeatable']),
  req('plaza-stall-goods', 'plaza', '杂货摊',
    'A market goods stall with wooden canopy, crates, displayed merchandise, game-ready 3D model',
    'high', 2.5, 2, ['plaza', 'repeatable']),
  req('plaza-stall-flower', 'plaza', '花摊',
    'A flower market stall with buckets of colorful flowers, wooden cart, awning, game-ready 3D model',
    'standard', 2, 3, ['plaza', 'repeatable']),
  req('plaza-bench-wood', 'plaza', '木长椅',
    'A wooden park bench with iron armrests, classic design, game-ready 3D model',
    'standard', 1, 3, ['plaza', 'repeatable']),
  req('plaza-bench-stone', 'plaza', '石长椅',
    'A stone garden bench with carved details, game-ready 3D model',
    'standard', 1, 3, ['plaza', 'repeatable']),
  req('plaza-lamp-post', 'plaza', '路灯',
    'A vintage cast iron street lamp with glowing lantern, ornate base, game-ready 3D model',
    'high', 4, 2, ['plaza', 'light', 'repeatable']),
  req('plaza-lamp-post-double', 'plaza', '双头路灯',
    'A double-lantern cast iron street lamp, ornate, game-ready 3D model',
    'standard', 4.5, 3, ['plaza', 'light', 'repeatable']),
  req('plaza-flag-pole', 'plaza', '旗杆',
    'A tall flagpole with a flowing yellow flag, game-ready 3D model',
    'standard', 6, 3, ['plaza', 'repeatable']),
  req('plaza-signpost', 'plaza', '指示牌',
    'A wooden signpost with multiple directional arrows, game-ready 3D model',
    'standard', 2.5, 3, ['plaza']),
  req('plaza-flowerbed', 'plaza', '花坛',
    'A circular stone flower bed with colorful blooming flowers, green foliage, game-ready 3D model',
    'standard', 1, 3, ['plaza', 'repeatable', 'nature']),
  req('plaza-flowerbed-rect', 'plaza', '长花坛',
    'A rectangular stone planter with flowers and small shrubs, game-ready 3D model',
    'standard', 0.8, 3, ['plaza', 'repeatable', 'nature']),
  req('plaza-trash-can', 'plaza', '垃圾桶',
    'A metal public trash can, game-ready 3D model',
    'standard', 1, 4, ['plaza', 'repeatable']),
  req('plaza-info-kiosk', 'plaza', '信息亭',
    'A small information kiosk booth with glass window, map display, game-ready 3D model',
    'standard', 2.5, 3, ['plaza']),
  req('plaza-outdoor-seating', 'plaza', '户外桌椅',
    'A set of outdoor cafe table and chairs, wrought iron, game-ready 3D model',
    'standard', 1.5, 3, ['plaza', 'repeatable']),
  req('plaza-bollard', 'plaza', '隔离桩',
    'A short stone bollard post with metal top, game-ready 3D model',
    'standard', 0.8, 4, ['plaza', 'repeatable']),
  req('plaza-planter-urn', 'plaza', '石瓮花盆',
    'An ornate stone urn planter with green plants, classical design, game-ready 3D model',
    'standard', 1.5, 3, ['plaza', 'repeatable']),
  req('plaza-bandstand', 'plaza', '音乐台',
    'A circular bandstand gazebo with domed roof, columns, game-ready 3D model',
    'high', 5, 2, ['plaza']),
  req('plaza-monument', 'plaza', '纪念碑',
    'An obelisk monument with inscriptions, stone, game-ready 3D model',
    'high', 8, 2, ['plaza', 'landmark']),
  req('plaza-sculpture-modern', 'plaza', '现代雕塑',
    'An abstract modern art sculpture, metal and polished stone, game-ready 3D model',
    'standard', 3, 3, ['plaza']),
];

// ─── 4. Props ───────────────────────────────────────────────────────────────
const props: AssetRequest[] = [
  req('prop-chest-wooden', 'props', '木箱宝箱',
    'A wooden treasure chest with metal bands and lock, slightly open with glowing interior, game-ready 3D model',
    'high', 1, 2, ['interactive', 'collectible']),
  req('prop-chest-golden', 'props', '金宝箱',
    'An ornate golden treasure chest with jewels, glowing runes, game-ready 3D model',
    'high', 1.2, 2, ['interactive', 'collectible', 'rare']),
  req('prop-barrel', 'props', '木桶',
    'A wooden barrel with metal hoops, game-ready 3D model',
    'standard', 1, 3, ['repeatable']),
  req('prop-crate', 'props', '木箱',
    'A wooden shipping crate, game-ready 3D model',
    'standard', 1, 3, ['repeatable']),
  req('prop-pot-clay', 'props', '陶罐',
    'A clay pottery jar, terracotta, game-ready 3D model',
    'standard', 0.8, 3, ['repeatable']),
  req('prop-torch-wall', 'props', '火把',
    'A wall-mounted torch with flickering flame, iron bracket, game-ready 3D model',
    'high', 1.5, 2, ['light', 'repeatable']),
  req('prop-lantern-paper', 'props', '纸灯笼',
    'A hanging red paper lantern with tassels, glowing, game-ready 3D model',
    'standard', 0.6, 3, ['light', 'repeatable']),
  req('prop-waypoint', 'props', '传送锚点',
    'A glowing magical teleport waypoint shrine, floating crystal, stone base, blue energy, game-ready 3D model',
    'high', 3, 1, ['interactive', 'teleport', 'landmark']),
  req('prop-portal-arch', 'props', '传送门',
    'A magical portal archway with swirling energy field, stone frame, glowing runes, game-ready 3D model',
    'high', 4, 2, ['interactive', 'teleport']),
  req('prop-crystal-blue', 'props', '蓝水晶',
    'A cluster of glowing blue crystals growing from rock, magical, game-ready 3D model',
    'high', 2, 2, ['collectible', 'light', 'repeatable']),
  req('prop-crystal-red', 'props', '红水晶',
    'A cluster of glowing red crystals, magical, game-ready 3D model',
    'high', 2, 2, ['collectible', 'light', 'repeatable']),
  req('prop-crystal-green', 'props', '绿水晶',
    'A cluster of glowing green crystals, magical, game-ready 3D model',
    'high', 2, 2, ['collectible', 'light', 'repeatable']),
  req('prop-coin-pile', 'props', '金币堆',
    'A pile of gold coins, shiny, game-ready 3D model',
    'standard', 0.3, 3, ['collectible', 'repeatable']),
  req('prop-cart-market', 'props', '摊位车',
    'A wooden market cart with wheels, canopy frame, game-ready 3D model',
    'standard', 2, 3, ['repeatable']),
  req('prop-balloon-cluster', 'props', '气球簇',
    'A cluster of colorful balloons tied together, floating, game-ready 3D model',
    'standard', 1.5, 3, ['repeatable']),
  req('prop-tent', 'props', '帐篷',
    'A canvas camping tent with entrance, guy ropes, game-ready 3D model',
    'high', 3, 2, ['repeatable']),
  req('prop-campfire', 'props', '篝火',
    'A campfire with burning logs and flames, stones around, game-ready 3D model',
    'high', 1, 2, ['light', 'repeatable']),
  req('prop-fence-wood', 'props', '木栅栏',
    'A wooden fence segment with two rails, posts, game-ready 3D model',
    'standard', 1.5, 3, ['repeatable', 'wall']),
  req('prop-fence-iron', 'props', '铁栅栏',
    'An iron fence segment with decorative bars, game-ready 3D model',
    'standard', 2, 3, ['repeatable', 'wall']),
  req('prop-sign-wooden', 'props', '木招牌',
    'A hanging wooden shop sign with bracket, game-ready 3D model',
    'standard', 1, 3, ['repeatable']),
  req('prop-barrel-stack', 'props', '木桶堆',
    'A stack of three wooden barrels, game-ready 3D model',
    'standard', 1.8, 3, ['repeatable']),
  req('prop-crate-stack', 'props', '木箱堆',
    'A stack of wooden crates, game-ready 3D model',
    'standard', 1.5, 3, ['repeatable']),
  req('prop-banner', 'props', '旗帜横幅',
    'A hanging fabric banner with emblem, waving, game-ready 3D model',
    'standard', 2, 3, ['repeatable']),
  req('prop-street-seller-cart', 'props', '小吃车',
    'A mobile food vendor cart with steam, cooking equipment, game-ready 3D model',
    'high', 2.5, 2, ['repeatable']),
  req('prop-garden-gnome', 'props', '花园小雕像',
    'A small garden gnome statue, colorful, game-ready 3D model',
    'standard', 0.5, 4, ['repeatable']),
  req('prop-bird-bath', 'props', '鸟浴盆',
    'A stone bird bath with water basin, game-ready 3D model',
    'standard', 1, 4, ['repeatable']),
  req('prop-mailbox', 'props', '邮筒',
    'A vintage red mailbox post, game-ready 3D model',
    'standard', 1.5, 4, ['repeatable']),
  req('prop-fountain-small', 'props', '小喷泉',
    'A small single-tier garden fountain, game-ready 3D model',
    'standard', 1.5, 3, ['repeatable', 'water']),
  req('prop-crystal-shard', 'props', '水晶碎片',
    'A single floating glowing crystal shard, collectible, game-ready 3D model',
    'standard', 0.5, 3, ['collectible', 'light', 'repeatable']),
  req('prop-treasure-sparkle', 'props', '闪光点',
    'A small glowing treasure sparkle effect marker on ground, game-ready 3D model',
    'standard', 0.3, 4, ['collectible', 'repeatable']),
];

// ─── 5. Nature ──────────────────────────────────────────────────────────────
const nature: AssetRequest[] = [
  // Trees
  req('nature-tree-oak', 'nature', '橡树',
    'A large oak tree with thick trunk, broad leafy canopy, green leaves, game-ready 3D model',
    'standard', 8, 3, ['tree', 'repeatable']),
  req('nature-tree-pine', 'nature', '松树',
    'A tall pine conifer tree with layered branches, dark green needles, game-ready 3D model',
    'standard', 10, 3, ['tree', 'repeatable']),
  req('nature-tree-sakura', 'nature', '樱花树',
    'A cherry blossom tree with pink flowers, spreading branches, game-ready 3D model',
    'high', 7, 2, ['tree', 'repeatable']),
  req('nature-tree-dead', 'nature', '枯树',
    'A dead leafless tree with twisted bare branches, spooky, game-ready 3D model',
    'standard', 7, 3, ['tree', 'repeatable']),
  req('nature-tree-maple', 'nature', '枫树',
    'A maple tree with red autumn leaves, game-ready 3D model',
    'standard', 7, 3, ['tree', 'repeatable']),
  req('nature-tree-willow', 'nature', '柳树',
    'A willow tree with drooping branches and green leaves, near water, game-ready 3D model',
    'standard', 8, 3, ['tree', 'repeatable']),
  req('nature-tree-palm', 'nature', '棕榈树',
    'A palm tree with fan leaves, tropical, game-ready 3D model',
    'standard', 7, 4, ['tree', 'repeatable']),
  req('nature-tree-birch', 'nature', '白桦树',
    'A birch tree with white bark and yellow leaves, game-ready 3D model',
    'standard', 8, 4, ['tree', 'repeatable']),
  // Bushes
  req('nature-bush-round', 'nature', '圆灌木',
    'A round green shrub bush, dense foliage, game-ready 3D model',
    'standard', 1.5, 3, ['bush', 'repeatable']),
  req('nature-bush-flower', 'nature', '开花灌木',
    'A flowering bush with pink blossoms, green leaves, game-ready 3D model',
    'standard', 1.2, 3, ['bush', 'repeatable']),
  req('nature-bush-hedge', 'nature', '绿篱',
    'A neatly trimmed rectangular hedge segment, game-ready 3D model',
    'standard', 1.5, 3, ['bush', 'repeatable', 'wall']),
  req('nature-bush-wild', 'nature', '野生灌木',
    'A wild unkempt bush with mixed foliage, game-ready 3D model',
    'standard', 1.5, 4, ['bush', 'repeatable']),
  // Rocks
  req('nature-rock-small', 'nature', '小石头',
    'A small gray rock, smooth, game-ready 3D model',
    'standard', 0.5, 3, ['rock', 'repeatable']),
  req('nature-rock-medium', 'nature', '中石头',
    'A medium-sized boulder, rough texture, game-ready 3D model',
    'standard', 1.5, 3, ['rock', 'repeatable']),
  req('nature-rock-large', 'nature', '巨石',
    'A large boulder with moss, cracks, game-ready 3D model',
    'standard', 3, 3, ['rock', 'repeatable']),
  req('nature-rock-cluster', 'nature', '石堆',
    'A cluster of rocks of various sizes, game-ready 3D model',
    'standard', 2, 3, ['rock', 'repeatable']),
  req('nature-mountain', 'nature', '山体',
    'A large mountain peak with rocky surface and sparse vegetation, game-ready 3D model',
    'high', 30, 2, ['rock', 'boundary']),
  req('nature-mountain-snow', 'nature', '雪山',
    'A snow-capped mountain peak, game-ready 3D model',
    'high', 35, 2, ['rock', 'boundary']),
  // Grass / flowers / mushrooms
  req('nature-grass-tuft', 'nature', '草丛',
    'A tuft of green grass blades, game-ready 3D model',
    'standard', 0.5, 4, ['grass', 'repeatable']),
  req('nature-flowers-wild', 'nature', '野花丛',
    'A patch of wild colorful flowers with green stems, game-ready 3D model',
    'standard', 0.4, 4, ['grass', 'repeatable']),
  req('nature-mushroom-red', 'nature', '红蘑菇',
    'Red mushrooms with white spots, growing, game-ready 3D model',
    'standard', 0.3, 4, ['repeatable']),
  req('nature-mushroom-glow', 'nature', '发光蘑菇',
    'Glowing blue mushrooms in dark setting, magical, game-ready 3D model',
    'high', 0.5, 3, ['light', 'repeatable']),
  // Water
  req('nature-lake', 'nature', '湖面',
    'A calm lake water surface plane with subtle ripples, blue-green, game-ready 3D model',
    'standard', 0.1, 2, ['water', 'boundary']),
  req('nature-river', 'nature', '河道',
    'A flowing river water segment, game-ready 3D model',
    'standard', 0.1, 3, ['water']),
  req('nature-waterfall', 'nature', '瀑布',
    'A waterfall cascading down rocks, mist, game-ready 3D model',
    'high', 10, 2, ['water', 'landmark']),
  req('nature-pond', 'nature', '池塘',
    'A small garden pond with lily pads, game-ready 3D model',
    'standard', 0.1, 3, ['water']),
  // Paths
  req('nature-path-stone', 'nature', '石板路',
    'A curved stone tile path segment, irregular slabs, game-ready 3D model',
    'standard', 0.1, 2, ['path', 'repeatable']),
  req('nature-path-dirt', 'nature', '土路',
    'A dirt road path segment, compacted earth, game-ready 3D model',
    'standard', 0.05, 3, ['path', 'repeatable']),
  req('nature-steps-stone', 'nature', '石阶',
    'A set of stone steps staircase, outdoor, game-ready 3D model',
    'standard', 1.5, 3, ['path', 'repeatable']),
];

// ─── 6. NPC placeholders ────────────────────────────────────────────────────
const npcs: AssetRequest[] = [
  req('npc-merchant', 'npc', '商人',
    'A neutral humanoid merchant character in simple clothing, standing pose, stylized low-poly, game-ready 3D model',
    'standard', 1.8, 3, ['npc']),
  req('npc-guard', 'npc', '守卫',
    'A neutral humanoid guard in light armor, standing pose, stylized low-poly, game-ready 3D model',
    'standard', 1.8, 3, ['npc']),
  req('npc-scholar', 'npc', '学者',
    'A neutral humanoid scholar with robe and book, standing pose, stylized low-poly, game-ready 3D model',
    'standard', 1.8, 3, ['npc']),
  req('npc-traveler', 'npc', '旅人',
    'A neutral humanoid traveler with backpack, standing pose, stylized low-poly, game-ready 3D model',
    'standard', 1.8, 3, ['npc']),
  req('npc-child', 'npc', '孩童',
    'A neutral humanoid child character, standing pose, stylized low-poly, game-ready 3D model',
    'standard', 1.4, 3, ['npc']),
];

// ─── 7. Style variants (high spec, to consume remaining credits) ────────────
// These provide visual variety and fill the credit budget.
const variantPrompts: Array<{ id: string; name: string; prompt: string; category: AssetRequest['category']; height: number }> = [
  // Building variants
  { id: 'building-court-alt', name: '法庭(夜景版)', prompt: 'A grand courthouse at dusk with warm lit windows, glowing entrance, dramatic lighting, neoclassical, game-ready 3D model', category: 'buildings', height: 12 },
  { id: 'building-tavern', name: '小酒馆', prompt: 'A cozy medieval tavern building with thatched roof, wooden beams, warm glowing windows, sign hanging, game-ready 3D model', category: 'buildings', height: 7 },
  { id: 'building-shop', name: '商店', prompt: 'A quaint medieval shop building with display window, awning, wooden sign, stone ground floor, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-house-cottage', name: '小屋', prompt: 'A charming cottage house with flower boxes, thatched roof, stone chimney, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-temple', name: '小神殿', prompt: 'A small ancient temple with columns, altar, weathered stone, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'building-windmill', name: '风车', prompt: 'A traditional Dutch windmill with rotating blades, stone base, game-ready 3D model', category: 'buildings', height: 12 },
  { id: 'building-barn', name: '谷仓', prompt: 'A red wooden barn with gambrel roof, farm setting, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'building-chapel', name: '小教堂', prompt: 'A small countryside chapel with steeple, stained glass, stone walls, game-ready 3D model', category: 'buildings', height: 10 },
  // Plaza variants
  { id: 'plaza-fountain-modern', name: '现代喷泉', prompt: 'A modern geometric fountain with vertical water jets, sleek design, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-statue-angel', name: '天使雕像', prompt: 'A winged angel statue on pedestal, marble, serene expression, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-statue-lion', name: '石狮', prompt: 'A stone lion guardian statue on pedestal, fierce expression, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-gazebo', name: '观景亭', prompt: 'A white wooden gazebo with lace-like trim, garden setting, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-bandstand-ornate', name: '华丽音乐台', prompt: 'An ornate Victorian bandstand with iron scrollwork, domed roof, game-ready 3D model', category: 'plaza', height: 6 },
  { id: 'plaza-memorial-wall', name: '纪念墙', prompt: 'A curved memorial wall with engraved names, fountain in front, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-clock-sundial', name: '日晷', prompt: 'A stone sundial in a garden, ornate base, game-ready 3D model', category: 'plaza', height: 1.5 },
  { id: 'plaza-globe-statue', name: '地球仪雕塑', prompt: 'A large metal globe sculpture on pedestal, rotating, game-ready 3D model', category: 'plaza', height: 4 },
  // Prop variants
  { id: 'prop-chest-ancient', name: '古老宝箱', prompt: 'An ancient stone sarcophagus-style chest with hieroglyphs, glowing cracks, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-chest-frost', name: '冰霜宝箱', prompt: 'A frost-covered treasure chest with ice crystals, blue glow, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-altar', name: '祭坛', prompt: 'A stone altar with glowing runes, offering bowl, magical, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-crystal-purple', name: '紫水晶', prompt: 'A cluster of glowing purple amethyst crystals, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-crystal-gold', name: '金水晶', prompt: 'A cluster of glowing golden crystals, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-orb-floating', name: '浮空宝珠', prompt: 'A floating magical orb with swirling energy, pedestal base, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-brazier', name: '火盆', prompt: 'A large stone brazier with burning fire, ornate metal bowl, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-cannon', name: '古炮', prompt: 'An antique bronze cannon on wooden carriage, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-well', name: '古井', prompt: 'A stone well with wooden roof and bucket, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-harbor-crane', name: '码头吊机', prompt: 'A wooden harbor crane for loading ships, game-ready 3D model', category: 'props', height: 8 },
  { id: 'prop-wheel-water', name: '水车', prompt: 'A wooden water wheel attached to a building, game-ready 3D model', category: 'props', height: 6 },
  { id: 'prop-telegraph', name: '电报杆', prompt: 'A vintage telegraph pole with crossarms and wires, game-ready 3D model', category: 'props', height: 7 },
  { id: 'prop-bench-park', name: '公园椅', prompt: 'A green painted metal and wood park bench, game-ready 3D model', category: 'props', height: 1 },
  // Nature variants
  { id: 'nature-tree-ginkgo', name: '银杏树', prompt: 'A ginkgo biloba tree with golden yellow fan-shaped leaves, game-ready 3D model', category: 'nature', height: 8 },
  { id: 'nature-tree-bonsai-large', name: '大盆景松', prompt: 'A large sculpted pine tree in decorative pot, garden feature, game-ready 3D model', category: 'nature', height: 3 },
  { id: 'nature-tree-cypress', name: '柏树', prompt: 'A tall narrow cypress tree, dark green, game-ready 3D model', category: 'nature', height: 9 },
  { id: 'nature-bush-topiary', name: '修剪灌木', prompt: 'A topiary bush sculpted into a spiral shape, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-bush-topiary-ball', name: '球形修剪', prompt: 'A perfectly round topiary ball on a stem, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-rock-mossy', name: '苔藓石', prompt: 'A moss-covered boulder with ferns, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-rock-pillar', name: '石柱', prompt: 'A tall natural rock pillar hoodoo, sedimentary layers, game-ready 3D model', category: 'nature', height: 12 },
  { id: 'nature-rock-arch', name: '石拱', prompt: 'A natural rock arch formation, game-ready 3D model', category: 'nature', height: 8 },
  { id: 'nature-islet', name: '小岛', prompt: 'A small rocky islet with grass and a tree, surrounded by water, game-ready 3D model', category: 'nature', height: 3 },
  { id: 'nature-reeds', name: '芦苇丛', prompt: 'A clump of tall reeds/cattails growing at water edge, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-lotus', name: '荷花', prompt: 'Lotus flowers and lily pads floating on water, game-ready 3D model', category: 'nature', height: 0.3 },
  { id: 'nature-bamboo', name: '竹林', prompt: 'A cluster of bamboo stalks with leaves, game-ready 3D model', category: 'nature', height: 6 },
  { id: 'nature-cactus', name: '仙人掌', prompt: 'A saguaro cactus with arms, desert, game-ready 3D model', category: 'nature', height: 4 },
  { id: 'nature-fern', name: '蕨类', prompt: 'A large fern plant with unfurling fronds, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-ivy', name: '常春藤', prompt: 'A patch of ivy climbing on a stone wall segment, game-ready 3D model', category: 'nature', height: 2 },
  // More plaza / city variants
  { id: 'plaza-ticket-booth', name: '售票亭', prompt: 'A small ticket booth with window and awning, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-photo-spot', name: '打卡点', prompt: 'A decorative photo spot frame with flowers and signage, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-outdoor-gym', name: '户外健身器', prompt: 'Outdoor gym exercise equipment, metal, game-ready 3D model', category: 'plaza', height: 2 },
  { id: 'plaza-playground-slide', name: '滑梯', prompt: 'A children playground slide with platform, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-playground-swing', name: '秋千', prompt: 'A swing set with two swings, metal frame, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-skate-ramp', name: '滑板坡道', prompt: 'A skateboard half-pipe ramp, game-ready 3D model', category: 'plaza', height: 2 },
  { id: 'plaza-food-truck', name: '餐车', prompt: 'A colorful food truck van with serving window, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-icecream-cart', name: '冰淇淋车', prompt: 'A vintage ice cream cart with umbrella, game-ready 3D model', category: 'plaza', height: 2 },
  { id: 'plaza-balloon-vendor', name: '气球小贩', prompt: 'A balloon vendor cart with many colorful balloons, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-street-performer', name: '街头艺人', prompt: 'A street performer stage with microphone stand and guitar case, game-ready 3D model', category: 'plaza', height: 1.8 },
  // More building variants
  { id: 'building-blacksmith', name: '铁匠铺', prompt: 'A medieval blacksmith forge building with chimney, anvil outside, glowing forge, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-clock-shop', name: '钟表店', prompt: 'A clockmaker shop with large clock on facade, gears visible, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-toy-shop', name: '玩具店', prompt: 'A colorful toy shop with whimsical facade, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-laundry', name: '洗衣店', prompt: 'A vintage laundry shop with hanging clothes outside, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-post-office', name: '邮局', prompt: 'A small post office building with blue sign, mailbox outside, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-fire-station', name: '消防站', prompt: 'A small fire station with red doors and pole, game-ready 3D model', category: 'buildings', height: 7 },
  { id: 'building-police-box', name: '警察岗亭', prompt: 'A British-style blue police box, game-ready 3D model', category: 'buildings', height: 3 },
  // More props
  { id: 'prop-pirate-chest', name: '海盗宝箱', prompt: 'A pirate treasure chest overflowing with gold coins and jewels, skull motif, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-mimic-chest', name: ' Mimic宝箱怪', prompt: 'A mimic chest monster with teeth and tongue, fantasy, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-soul-orb', name: '灵魂宝珠', prompt: 'A glowing soul orb floating above a stone base, ethereal blue, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-elemental-fire', name: '火元素', prompt: 'A small fire elemental creature, dancing flames, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-elemental-ice', name: '冰元素', prompt: 'A small ice elemental creature, crystalline blue, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-sundial-large', name: '大型日晷', prompt: 'A large ornate sundial in a plaza, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-flag-banner-tall', name: '高旗帜', prompt: 'A tall banner flag on a pole, flowing fabric, game-ready 3D model', category: 'props', height: 8 },
  { id: 'prop-market-awning', name: '市集遮阳篷', prompt: 'A striped market stall awning canopy, game-ready 3D model', category: 'props', height: 2.5 },
  // More nature
  { id: 'nature-tree-autumn', name: '秋树', prompt: 'An autumn tree with orange and yellow leaves, game-ready 3D model', category: 'nature', height: 7 },
  { id: 'nature-tree-winter', name: '冬树', prompt: 'A snow-covered bare tree, winter, game-ready 3D model', category: 'nature', height: 7 },
  { id: 'nature-tree-spring', name: '春树', prompt: 'A spring tree with fresh light green leaves and blossoms, game-ready 3D model', category: 'nature', height: 7 },
  { id: 'nature-bush-autumn', name: '秋灌木', prompt: 'An autumn bush with orange-red foliage, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-rock-snow', name: '雪石', prompt: 'A snow-capped boulder, winter scene, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-ice-floe', name: '浮冰', prompt: 'A floating ice floe piece, arctic, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-coral', name: '珊瑚', prompt: 'A colorful coral reef formation, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-seaweed', name: '海草', prompt: 'Tall swaying seaweed underwater, game-ready 3D model', category: 'nature', height: 3 },
  { id: 'nature-mushroom-giant', name: '巨型蘑菇', prompt: 'A giant fantasy mushroom tree, red cap with white spots, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-glowing-plant', name: '发光植物', prompt: 'A bioluminescent glowing plant, fantasy, game-ready 3D model', category: 'nature', height: 1 },
  // More city / plaza
  { id: 'city-fountain-dragon', name: '龙喷泉', prompt: 'A fountain with a dragon statue spouting water, ornate, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'city-fountain-horse', name: '马喷泉', prompt: 'A fountain with rearing horse statues, classical, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'city-statue-eagle', name: '鹰雕像', prompt: 'A statue of an eagle with spread wings on pedestal, bronze, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'city-statue-dragon', name: '龙雕像', prompt: 'A coiled dragon statue, Eastern style, stone, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'city-gate-torii', name: '鸟居', prompt: 'A traditional Japanese torii gate, vermilion red, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'city-gate-paifang', name: '牌坊', prompt: 'A traditional Chinese paifang archway with tiled roof, game-ready 3D model', category: 'buildings', height: 9 },
  { id: 'city-bridge-rainbow', name: '彩虹桥', prompt: 'A colorful rainbow-painted pedestrian bridge, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'city-bridge-suspension', name: '吊桥', prompt: 'A wooden rope suspension bridge, game-ready 3D model', category: 'buildings', height: 2 },
  { id: 'plaza-bench-modern', name: '现代长椅', prompt: 'A modern minimalist concrete and wood bench, game-ready 3D model', category: 'plaza', height: 0.8 },
  { id: 'plaza-lamp-solar', name: '太阳能路灯', prompt: 'A modern solar-powered LED street lamp, sleek, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-trash-recycle', name: '分类垃圾桶', prompt: 'A set of recycling bins color-coded, game-ready 3D model', category: 'plaza', height: 1 },
  { id: 'plaza-bike-rack', name: '自行车架', prompt: 'A metal bike rack with a bicycle parked, game-ready 3D model', category: 'plaza', height: 1.2 },
  { id: 'plaza-outlet', name: '充电桩', prompt: 'An EV charging station, modern, game-ready 3D model', category: 'plaza', height: 1.8 },
  { id: 'plaza-news-stand', name: '报刊亭', prompt: 'A vintage newsstand kiosk with magazines displayed, game-ready 3D model', category: 'plaza', height: 2.5 },
  // More props for credit consumption
  { id: 'prop-vending-machine', name: '自动售货机', prompt: 'A Japanese-style vending machine with drinks, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-jukebox', name: '点唱机', prompt: 'A vintage jukebox with glowing lights, game-ready 3D model', category: 'props', height: 1.8 },
  { id: 'prop-pinball', name: '弹珠机', prompt: 'A retro pinball machine, colorful, game-ready 3D model', category: 'props', height: 1.8 },
  { id: 'prop-arcade-cabinet', name: '街机', prompt: 'A retro arcade game cabinet with screen, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-gumball-machine', name: '扭蛋机', prompt: 'A gumball vending machine, glass globe, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-claw-machine', name: '抓娃娃机', prompt: 'A claw machine arcade game with plush toys inside, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-photo-booth', name: '拍照亭', prompt: 'A vintage photo booth curtained, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-popcorn-machine', name: '爆米花机', prompt: 'A commercial popcorn machine with red and white stripes, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-cotton-candy', name: '棉花糖机', prompt: 'A cotton candy machine with pink cotton candy, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-snow-cone', name: '刨冰机', prompt: 'A shaved ice machine with colorful syrups, game-ready 3D model', category: 'props', height: 1.2 },
  // More buildings
  { id: 'building-cinema', name: '电影院', prompt: 'An art deco cinema building with neon marquee and ticket booth, game-ready 3D model', category: 'buildings', height: 10 },
  { id: 'building-bowling', name: '保龄球馆', prompt: 'A bowling alley building with retro signage, game-ready 3D model', category: 'buildings', height: 7 },
  { id: 'building-karaoke', name: 'KTV', prompt: 'A karaoke box building with neon lights, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'building-casino', name: '娱乐场', prompt: 'A casino building with flashing lights and grand entrance, game-ready 3D model', category: 'buildings', height: 12 },
  { id: 'building-bathhouse', name: '澡堂', prompt: 'A traditional public bathhouse building with steam, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-laundromat', name: '自助洗衣店', prompt: 'A laundromat with washing machines visible through window, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-pawn-shop', name: '当铺', prompt: 'A pawn shop with barred window and gold ball sign, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-pet-shop', name: '宠物店', prompt: 'A pet shop with cute animals in window, game-ready 3D model', category: 'buildings', height: 5 },
  // More nature for boundary / variety
  { id: 'nature-cliff', name: '悬崖', prompt: 'A tall cliff face with layered rock, game-ready 3D model', category: 'nature', height: 15 },
  { id: 'nature-cave-entrance', name: '洞穴入口', prompt: 'A cave entrance in a rocky hillside, dark interior, game-ready 3D model', category: 'nature', height: 6 },
  { id: 'nature-hill', name: '山丘', prompt: 'A rolling grassy hill mound, game-ready 3D model', category: 'nature', height: 8 },
  { id: 'nature-sand-dune', name: '沙丘', prompt: 'A sand dune formation, desert, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-hot-spring', name: '温泉', prompt: 'A natural hot spring with steaming water and rocks, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-geyser', name: '间歇泉', prompt: 'A geyser erupting with steam and water, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-volcano-small', name: '小火山', prompt: 'A small volcano with smoking crater, game-ready 3D model', category: 'nature', height: 12 },
  { id: 'nature-mangrove', name: '红树林', prompt: 'Mangrove trees with exposed roots in water, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-sequoia', name: '红杉', prompt: 'A giant sequoia tree with massive trunk, game-ready 3D model', category: 'nature', height: 20 },
  { id: 'nature-baobab', name: '猴面包树', prompt: 'A baobab tree with thick trunk and sparse branches, game-ready 3D model', category: 'nature', height: 12 },
  // Final batch of high-spec variants to ensure credit consumption
  { id: 'building-mansion', name: '大庄园', prompt: 'A grand mansion estate with columns, balcony, landscaped grounds, game-ready 3D model', category: 'buildings', height: 14 },
  { id: 'building-castle-keep', name: '城堡主楼', prompt: 'A medieval castle keep with towers and battlements, stone, game-ready 3D model', category: 'buildings', height: 18 },
  { id: 'building-cathedral', name: '大教堂', prompt: 'A gothic cathedral with stained glass, spires, flying buttresses, game-ready 3D model', category: 'buildings', height: 20 },
  { id: 'building-mosque', name: '清真寺', prompt: 'A mosque with dome and minaret, geometric patterns, game-ready 3D model', category: 'buildings', height: 16 },
  { id: 'building-pagoda', name: '宝塔', prompt: 'A multi-tiered Chinese pagoda with curved roofs, game-ready 3D model', category: 'buildings', height: 18 },
  { id: 'building-stupa', name: '佛塔', prompt: 'A Buddhist stupa with golden dome, game-ready 3D model', category: 'buildings', height: 12 },
  { id: 'building-obelisk-tall', name: '方尖碑', prompt: 'A tall Egyptian obelisk with hieroglyphs, game-ready 3D model', category: 'buildings', height: 20 },
  { id: 'building-colosseum', name: '角斗场', prompt: 'A miniature colosseum amphitheater, weathered stone, game-ready 3D model', category: 'buildings', height: 12 },
  { id: 'building-pyramid', name: '金字塔', prompt: 'A small step pyramid, Mayan style, with stairs, game-ready 3D model', category: 'buildings', height: 10 },
  { id: 'building-sphinx', name: '狮身人面像', prompt: 'A sphinx statue with lion body and human head, game-ready 3D model', category: 'buildings', height: 8 },
  // ─── Additional batch 1: more buildings ───
  { id: 'building-observatory', name: '天文台', prompt: 'An observatory with a domed roof and telescope, stone building, game-ready 3D model', category: 'buildings', height: 10 },
  { id: 'building-zoo-entrance', name: '动物园入口', prompt: 'A zoo entrance gate with animal motifs and ticket booths, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'building-amusement-park', name: '游乐园入口', prompt: 'An amusement park entrance with colorful arches and ticket booths, game-ready 3D model', category: 'buildings', height: 10 },
  { id: 'building-ferris-wheel', name: '摩天轮', prompt: 'A Ferris wheel with colorful gondolas, amusement park, game-ready 3D model', category: 'buildings', height: 25 },
  { id: 'building-carousel', name: '旋转木马', prompt: 'A classic carousel with painted horses and canopy, game-ready 3D model', category: 'buildings', height: 6 },
  { id: 'building-roller-coaster', name: '过山车', prompt: 'A roller coaster track section with support structure, game-ready 3D model', category: 'buildings', height: 15 },
  { id: 'building-bumper-cars', name: '碰碰车', prompt: 'A bumper car arena with cars and electrified ceiling, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-haunted-house', name: '鬼屋', prompt: 'A spooky haunted house attraction with crooked architecture and eerie lighting, game-ready 3D model', category: 'buildings', height: 9 },
  { id: 'building-mirror-maze', name: '镜子迷宫', prompt: 'A mirror maze attraction with glass walls and neon lights, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-arcade-outdoor', name: '户外街机', prompt: 'An outdoor arcade area with multiple game cabinets, game-ready 3D model', category: 'buildings', height: 4 },
  { id: 'building-mini-golf', name: '迷你高尔夫', prompt: 'A mini golf course hole with obstacles and windmill, game-ready 3D model', category: 'buildings', height: 4 },
  { id: 'building-go-kart', name: '卡丁车赛道', prompt: 'A go-kart track with barriers and a kart, game-ready 3D model', category: 'buildings', height: 3 },
  { id: 'building-batting-cage', name: '击球笼', prompt: 'A batting cage with netting and pitching machine, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-mini-bowling', name: '迷你保龄球', prompt: 'A mini bowling alley lane with pins and ball, game-ready 3D model', category: 'buildings', height: 3 },
  { id: 'building-shooting-gallery', name: '射击场', prompt: 'A shooting gallery with targets and gallery front, game-ready 3D model', category: 'buildings', height: 4 },
  { id: 'building-ring-toss', name: '套圈摊位', prompt: 'A ring toss carnival game booth with prizes, game-ready 3D model', category: 'buildings', height: 3 },
  { id: 'building-dunk-tank', name: '投球落水', prompt: 'A dunk tank carnival attraction with seat and water tank, game-ready 3D model', category: 'buildings', height: 4 },
  { id: 'building-cotton-candy-stand', name: '棉花糖摊', prompt: 'A cotton candy stand with pink cotton candy and machine, game-ready 3D model', category: 'buildings', height: 2.5 },
  // ─── Additional batch 2: more plaza features ───
  { id: 'plaza-fountain-horse', name: '马形喷泉', prompt: 'A fountain with horse statues spraying water, baroque style, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-fountain-turtle', name: '龟形喷泉', prompt: 'A fountain with turtle statues, whimsical, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-fountain-geometric', name: '几何喷泉', prompt: 'A modern geometric fountain with stacked cubes and water, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-statue-mermaid', name: '美人鱼雕像', prompt: 'A mermaid statue on a rock pedestal, bronze, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-statue-warrior', name: '战士雕像', prompt: 'A warrior statue with sword and shield, heroic pose, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-statue-dancer', name: '舞者雕像', prompt: 'A statue of a dancer in dynamic pose, bronze, game-ready 3D model', category: 'plaza', height: 3.5 },
  { id: 'plaza-statue-thinker', name: '思想者雕像', prompt: 'A thinker statue in contemplative pose, bronze, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-statue-horse', name: '马雕像', prompt: 'A rearing horse statue on pedestal, bronze, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-statue-dragon-east', name: '东方龙雕像', prompt: 'An Eastern dragon statue coiled around pillar, golden, game-ready 3D model', category: 'plaza', height: 6 },
  { id: 'plaza-clock-sundial-stone', name: '石日晷', prompt: 'A stone sundial with Roman numerals, garden, game-ready 3D model', category: 'plaza', height: 1.5 },
  { id: 'plaza-globe-metal', name: '金属地球仪', prompt: 'A large metal globe sculpture with axis, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-infinity-fountain', name: '无边喷泉', prompt: 'An infinity edge fountain with water flowing over edge, modern, game-ready 3D model', category: 'plaza', height: 2 },
  { id: 'plaza-mosaic-floor', name: '马赛克地面', prompt: 'A circular mosaic floor medallion with intricate pattern, game-ready 3D model', category: 'plaza', height: 0.1 },
  { id: 'plaza-kiosk-information', name: '信息亭', prompt: 'A modern information kiosk with digital screen, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-kiosk-ticket', name: '售票亭', prompt: 'A ticket booth kiosk with window and signage, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-kiosk-photo', name: '拍照亭', prompt: 'A photo booth kiosk with curtain and flash, game-ready 3D model', category: 'plaza', height: 2.5 },
  { id: 'plaza-seat-wavy', name: '波浪座椅', prompt: 'A modern wavy public bench sculpture, game-ready 3D model', category: 'plaza', height: 1 },
  { id: 'plaza-seat-circle', name: '环形座椅', prompt: 'A circular bench around a tree planter, game-ready 3D model', category: 'plaza', height: 0.8 },
  { id: 'plaza-lamp-solar-modern', name: '现代太阳能灯', prompt: 'A modern solar-powered LED street lamp with sleek design, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-lamp-harbor', name: '码头灯', prompt: 'A harbor-style lamp post with cage light, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-lamp-tiffany', name: '蒂芙尼灯', prompt: 'A Tiffany-style stained glass lamp post, colorful, game-ready 3D model', category: 'plaza', height: 3.5 },
  { id: 'plaza-flag-banner', name: '横幅旗帜', prompt: 'A hanging banner flag between two poles, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-pennant-string', name: '三角旗串', prompt: 'A string of colorful pennant flags, festival, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'plaza-decorative-column', name: '装饰柱', prompt: 'A decorative classical column with capital and base, game-ready 3D model', category: 'plaza', height: 5 },
  // ─── Additional batch 3: more props ───
  { id: 'prop-chest-royal', name: '皇家宝箱', prompt: 'A royal treasure chest with velvet lining and gold trim, glowing, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-chest-cursed', name: '诅咒宝箱', prompt: 'A cursed treasure chest with dark energy and skull lock, game-ready 3D model', category: 'props', height: 1.1 },
  { id: 'prop-chest-ice', name: '冰封宝箱', prompt: 'An ice-encased treasure chest frozen in a block of ice, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-chest-lava', name: '熔岩宝箱', prompt: 'A lava-themed chest with glowing cracks and heat haze, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-urn-ancient', name: '古瓮', prompt: 'An ancient ceramic urn with Greek patterns, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-urn-jade', name: '玉瓮', prompt: 'A jade green urn with carved patterns, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-vase-blue', name: '青花瓷瓶', prompt: 'A blue and white porcelain vase with floral patterns, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-vase-gold', name: '金瓶', prompt: 'A golden ornate vase with engravings, game-ready 3D model', category: 'props', height: 1.3 },
  { id: 'prop-statue-small-greek', name: '希腊小雕像', prompt: 'A small Greek statue of a deity, marble, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-statue-bust', name: '半身像', prompt: 'A marble bust sculpture on pedestal, game-ready 3D model', category: 'props', height: 1.8 },
  { id: 'prop-globe-vintage', name: '复古地球仪', prompt: 'A vintage world globe on wooden stand, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-telescope', name: '望远镜', prompt: 'A brass telescope on tripod, vintage, game-ready 3D model', category: 'props', height: 1.8 },
  { id: 'prop-hourglass-giant', name: '巨型沙漏', prompt: 'A giant hourglass with flowing sand, decorative, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-sundial-small', name: '小型日晷', prompt: 'A small garden sundial on pedestal, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-birdhouse', name: '鸟屋', prompt: 'A decorative birdhouse on pole, painted, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-beehive', name: '蜂箱', prompt: 'A wooden beehive with bees, garden, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-wheel-water-small', name: '小水车', prompt: 'A small decorative water wheel in garden stream, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-windmill-small', name: '小风车', prompt: 'A small decorative garden windmill, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-butterfly-house', name: '蝴蝶屋', prompt: 'A butterfly house with flowers and netting, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-compass-stone', name: '石罗盘', prompt: 'A compass rose embedded in stone pavement, bronze inlay, game-ready 3D model', category: 'props', height: 0.15 },
  { id: 'prop-manhole', name: '井盖', prompt: 'A decorative manhole cover with city emblem, game-ready 3D model', category: 'props', height: 0.05 },
  { id: 'prop-drain-cover', name: '排水篦子', prompt: 'A metal drain grate cover, game-ready 3D model', category: 'props', height: 0.05 },
  { id: 'prop-fire-hydrant', name: '消防栓', prompt: 'A red fire hydrant, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-parking-meter', name: '停车计时器', prompt: 'A vintage parking meter on pole, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-newspaper-stand', name: '报刊架', prompt: 'A newspaper stand with magazines, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-sandwich-board', name: 'A型广告牌', prompt: 'A sandwich board A-frame sign, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-traffic-cone', name: '交通锥', prompt: 'An orange traffic cone with white stripes, game-ready 3D model', category: 'props', height: 0.8 },
  { id: 'prop-barricade', name: '路障', prompt: 'A wooden police barricade with stripes, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-planter-hanging', name: '吊篮花盆', prompt: 'A hanging flower basket with trailing plants, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-window-box', name: '窗盒花', prompt: 'A window box with colorful flowers, game-ready 3D model', category: 'props', height: 0.6 },
  { id: 'prop-trellis', name: '花架', prompt: 'A wooden trellis with climbing roses, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-pergola', name: '藤架', prompt: 'A wooden pergola with climbing vines, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-arch-flowers', name: '花拱门', prompt: 'A flower-covered archway for events, game-ready 3D model', category: 'props', height: 3.5 },
  { id: 'prop-gazebo-small', name: '小露台', prompt: 'A small garden gazebo with lattice sides, game-ready 3D model', category: 'props', height: 4 },
  { id: 'prop-swing-bench', name: '秋千椅', prompt: 'A hanging swing bench with chains, garden, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-hammock', name: '吊床', prompt: 'A hammock between two posts, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-picnic-table', name: '野餐桌', prompt: 'A wooden picnic table with attached benches, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-bbq-grill', name: '烧烤架', prompt: 'A barbecue grill with charcoal and tools, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-bird-feeder', name: '喂鸟器', prompt: 'A hanging bird feeder with seed, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-fairy-door', name: '精灵门', prompt: 'A tiny fairy door on a tree trunk, magical, game-ready 3D model', category: 'props', height: 0.5 },
  // ─── Additional batch 4: more nature ───
  { id: 'nature-tree-elm', name: '榆树', prompt: 'An elm tree with broad vase-shaped canopy, game-ready 3D model', category: 'nature', height: 10 },
  { id: 'nature-tree-ash', name: '白蜡树', prompt: 'An ash tree with compound leaves, game-ready 3D model', category: 'nature', height: 9 },
  { id: 'nature-tree-chestnut', name: '栗树', prompt: 'A chestnut tree with spiky seed pods, game-ready 3D model', category: 'nature', height: 10 },
  { id: 'nature-tree-walnut', name: '胡桃树', prompt: 'A walnut tree with large leaves, game-ready 3D model', category: 'nature', height: 9 },
  { id: 'nature-tree-cherry', name: '樱桃树', prompt: 'A cherry tree with red fruit, game-ready 3D model', category: 'nature', height: 6 },
  { id: 'nature-tree-apple', name: '苹果树', prompt: 'An apple tree with red apples, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-tree-orange', name: '橘子树', prompt: 'An orange tree with citrus fruit, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-tree-lemon', name: '柠檬树', prompt: 'A lemon tree with yellow fruit, game-ready 3D model', category: 'nature', height: 4.5 },
  { id: 'nature-tree-olive', name: '橄榄树', prompt: 'An olive tree with silvery leaves and gnarled trunk, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-tree-bonsai', name: '盆景', prompt: 'A bonsai tree in ceramic pot, carefully pruned, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-bush-lavender', name: '薰衣草', prompt: 'A lavender bush with purple flowers, game-ready 3D model', category: 'nature', height: 0.8 },
  { id: 'nature-bush-rose', name: '玫瑰丛', prompt: 'A rose bush with red flowers and thorns, game-ready 3D model', category: 'nature', height: 1.2 },
  { id: 'nature-bush-hydrangea', name: '绣球花', prompt: 'A hydrangea bush with blue flower clusters, game-ready 3D model', category: 'nature', height: 1.2 },
  { id: 'nature-bush-rhododendron', name: '杜鹃花', prompt: 'A rhododendron bush with pink flowers, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-bush-boxwood', name: '黄杨木', prompt: 'A boxwood hedge shrub, dense green, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-bush-holly', name: '冬青', prompt: 'A holly bush with red berries and spiky leaves, game-ready 3D model', category: 'nature', height: 1.2 },
  { id: 'nature-rock-volcanic', name: '火山岩', prompt: 'A volcanic rock with porous texture, dark, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-rock-crystal-geode', name: '晶洞', prompt: 'A cracked geode rock with purple crystals inside, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-rock-marble', name: '大理石', prompt: 'A polished marble boulder with veins, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-rock-slate', name: '板岩', prompt: 'A slate rock formation with layered flat stones, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-rock-granite', name: '花岗岩', prompt: 'A granite boulder with speckled texture, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-rock-limestone', name: '石灰岩', prompt: 'A limestone rock with erosion patterns, game-ready 3D model', category: 'nature', height: 2.5 },
  { id: 'nature-flower-sunflower', name: '向日葵', prompt: 'A cluster of sunflowers with tall stems, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-flower-tulip', name: '郁金香', prompt: 'A bed of tulips in various colors, game-ready 3D model', category: 'nature', height: 0.6 },
  { id: 'nature-flower-rose', name: '玫瑰花', prompt: 'A cluster of rose bushes with blooms, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-flower-lavender-field', name: '薰衣草田', prompt: 'A patch of lavender field rows, game-ready 3D model', category: 'nature', height: 0.8 },
  { id: 'nature-grass-tall', name: '高草', prompt: 'Tall ornamental grass plumes, game-ready 3D model', category: 'nature', height: 1.5 },
  { id: 'nature-grass-pampas', name: '蒲苇', prompt: 'Pampas grass with feathery plumes, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-moss-rock', name: '苔藓石', prompt: 'A moss-covered rock with small ferns, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-lichen-stone', name: '地衣石', prompt: 'A stone with colorful lichen patches, game-ready 3D model', category: 'nature', height: 0.8 },
  { id: 'nature-log-mossy', name: '苔藓原木', prompt: 'A fallen mossy log with mushrooms, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-stump', name: '树桩', prompt: 'A tree stump with rings and moss, game-ready 3D model', category: 'nature', height: 0.8 },
  { id: 'nature-stump-hollow', name: '空心树桩', prompt: 'A hollow tree stump with glowing interior, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-branch-dead', name: '枯枝', prompt: 'A pile of dead branches and twigs, game-ready 3D model', category: 'nature', height: 0.8 },
  { id: 'nature-pinecone', name: '松果', prompt: 'A large pine cone on ground, game-ready 3D model', category: 'nature', height: 0.3 },
  { id: 'nature-acorn', name: '橡果', prompt: 'A cluster of acorns on ground, game-ready 3D model', category: 'nature', height: 0.1 },
  { id: 'nature-water-lily', name: '睡莲', prompt: 'Water lily pads with pink flowers on pond, game-ready 3D model', category: 'nature', height: 0.2 },
  { id: 'nature-cattail', name: '香蒲', prompt: 'Cattail reeds at water edge, game-ready 3D model', category: 'nature', height: 1.8 },
  { id: 'nature-stream', name: '溪流', prompt: 'A shallow stream with rocks and clear water, game-ready 3D model', category: 'nature', height: 0.2 },
  { id: 'nature-rapids', name: '急流', prompt: 'White water rapids with rocks and foam, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-waterfall-small', name: '小瀑布', prompt: 'A small waterfall over rocks into pool, game-ready 3D model', category: 'nature', height: 4 },
  { id: 'nature-hot-spring-rock', name: '岩石温泉', prompt: 'A natural hot spring pool surrounded by rocks with steam, game-ready 3D model', category: 'nature', height: 1 },
  { id: 'nature-ice-pond', name: '冰池', prompt: 'A frozen pond with cracked ice surface, game-ready 3D model', category: 'nature', height: 0.1 },
  { id: 'nature-snow-patch', name: '积雪', prompt: 'A patch of melting snow on ground, game-ready 3D model', category: 'nature', height: 0.2 },
  { id: 'nature-sand-patch', name: '沙地', prompt: 'A patch of sandy ground with small pebbles, game-ready 3D model', category: 'nature', height: 0.05 },
  { id: 'nature-mud-puddle', name: '泥坑', prompt: 'A muddy puddle with ripples, game-ready 3D model', category: 'nature', height: 0.1 },
  { id: 'nature-leaf-pile', name: '落叶堆', prompt: 'A pile of autumn leaves in orange and red, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-flower-wild-purple', name: '紫野花', prompt: 'A patch of wild purple flowers, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-flower-wild-yellow', name: '黄野花', prompt: 'A patch of wild yellow flowers, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-flower-wild-white', name: '白野花', prompt: 'A patch of wild white daisies, game-ready 3D model', category: 'nature', height: 0.5 },
  { id: 'nature-mushroom-brown', name: '棕蘑菇', prompt: 'A cluster of brown cap mushrooms, game-ready 3D model', category: 'nature', height: 0.2 },
  { id: 'nature-mushroom-white', name: '白蘑菇', prompt: 'White button mushrooms growing, game-ready 3D model', category: 'nature', height: 0.15 },
  { id: 'nature-mushroom-amanita', name: '毒蝇伞', prompt: 'Red fly agaric mushrooms with white spots, game-ready 3D model', category: 'nature', height: 0.3 },
  { id: 'nature-mushroom-glow-blue', name: '蓝光蘑菇', prompt: 'Glowing blue bioluminescent mushrooms, fantasy, game-ready 3D model', category: 'nature', height: 0.4 },
  { id: 'nature-mushroom-glow-green', name: '绿光蘑菇', prompt: 'Glowing green bioluminescent mushrooms, fantasy, game-ready 3D model', category: 'nature', height: 0.4 },
  { id: 'nature-crystal-cave', name: '洞晶簇', prompt: 'A crystal cluster growing from cave wall, amethyst, game-ready 3D model', category: 'nature', height: 2 },
  { id: 'nature-stalactite', name: '钟乳石', prompt: 'Hanging stalactite formation from cave ceiling, game-ready 3D model', category: 'nature', height: 3 },
  { id: 'nature-stalagmite', name: '石笋', prompt: 'A stalagmite formation rising from cave floor, game-ready 3D model', category: 'nature', height: 2.5 },
  { id: 'nature-cave-pillar', name: '洞穴柱', prompt: 'A cave pillar where stalactite meets stalagmite, game-ready 3D model', category: 'nature', height: 5 },
  { id: 'nature-glowing-moss', name: '发光苔藓', prompt: 'Glowing green moss on rocks, fantasy cave, game-ready 3D model', category: 'nature', height: 0.3 },
  { id: 'nature-underground-lake', name: '地下湖', prompt: 'An underground lake with glowing blue water, cave setting, game-ready 3D model', category: 'nature', height: 0.2 },
  // ─── Additional batch 5: credit-burner high-spec assets ───
  { id: 'building-clocktower-grand', name: '大钟楼', prompt: 'A grand clock tower with giant clock face, bells, ornate stonework, game-ready 3D model', category: 'buildings', height: 22 },
  { id: 'building-windmill-large', name: '大风车', prompt: 'A large Dutch windmill with rotating blades, stone base, game-ready 3D model', category: 'buildings', height: 14 },
  { id: 'building-toyshop', name: '玩具店', prompt: 'A toy shop with colorful displays and toys in window, game-ready 3D model', category: 'buildings', height: 5 },
  { id: 'building-art-gallery', name: '美术馆', prompt: 'A modern art gallery with white walls and paintings, minimalist design, game-ready 3D model', category: 'buildings', height: 8 },
  { id: 'building-museum-small', name: '小博物馆', prompt: 'A small natural history museum with dinosaur skeleton visible, game-ready 3D model', category: 'buildings', height: 9 },
  { id: 'plaza-fountain-unicorn', name: '独角兽喷泉', prompt: 'A fountain with a unicorn statue spouting water, magical, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-fountain-dragon', name: '龙喷泉', prompt: 'A fountain with a coiled dragon statue, water from mouth, fantasy, game-ready 3D model', category: 'plaza', height: 6 },
  { id: 'plaza-fountain-cherub', name: '天使喷泉', prompt: 'A baroque fountain with cherub statues and ornate basin, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-statue-knight', name: '骑士雕像', prompt: 'A statue of a knight in armor on horseback, bronze, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-statue-mage', name: '法师雕像', prompt: 'A statue of a robed mage with staff and glowing orb, fantasy, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-gazebo-japanese', name: '日式凉亭', prompt: 'A Japanese-style gazebo with curved roof and wooden structure, game-ready 3D model', category: 'plaza', height: 5 },
  { id: 'plaza-gazebo-roman', name: '罗马凉亭', prompt: 'A Roman-style gazebo with marble columns and domed roof, game-ready 3D model', category: 'plaza', height: 6 },
  { id: 'plaza-bridge-arch', name: '拱桥', prompt: 'A stone arch bridge over water, classic design, game-ready 3D model', category: 'plaza', height: 4 },
  { id: 'plaza-bridge-wooden', name: '木桥', prompt: 'A wooden footbridge with railings over stream, game-ready 3D model', category: 'plaza', height: 2 },
  { id: 'plaza-bridge-suspension', name: '吊桥', prompt: 'A small suspension bridge with wooden planks and rope railings, game-ready 3D model', category: 'plaza', height: 3 },
  { id: 'prop-shrine-small', name: '小神龛', prompt: 'A small Shinto shrine with torii gate and offerings, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-altar-stone', name: '石祭坛', prompt: 'A stone altar with carved runes and candles, ancient, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-cauldron-large', name: '大坩埚', prompt: 'A large witch cauldron with bubbling green liquid and steam, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-broom-flying', name: '飞天扫帚', prompt: 'A magical flying broomstick hovering, fantasy, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-spellbook-open', name: '打开的魔法书', prompt: 'An open spellbook with glowing pages and floating runes, game-ready 3D model', category: 'props', height: 0.5 },
  { id: 'prop-potion-rack', name: '药水架', prompt: 'A wooden rack with colorful potion bottles, alchemy, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-crystal-ball', name: '水晶球', prompt: 'A crystal ball on ornate stand with swirling mist inside, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-treasure-pile', name: '财宝堆', prompt: 'A pile of gold coins, gems, and treasure, shiny, game-ready 3D model', category: 'props', height: 1 },
  { id: 'prop-anvil', name: '铁砧', prompt: 'A blacksmith anvil with hammer and sparks, workshop, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-weapon-rack', name: '武器架', prompt: 'A rack with swords, axes, and shields, medieval, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-target-archery', name: '射箭靶', prompt: 'An archery target with arrows stuck in it, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-music-stand', name: '谱架', prompt: 'A music stand with sheet music, vintage, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-piano-grand', name: '三角钢琴', prompt: 'A grand piano with open lid and bench, elegant, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-harp', name: '竖琴', prompt: 'A golden harp with strings, ornate, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-chess-giant', name: '巨型国际象棋', prompt: 'A giant chess piece (king) on board, outdoor, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-flamingo-lawn', name: '草坪火烈鸟', prompt: 'A pink plastic flamingo lawn ornament, retro, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-bathtub-clawfoot', name: '爪足浴缸', prompt: 'A vintage clawfoot bathtub with bubbles, quirky, game-ready 3D model', category: 'props', height: 1.5 },
  { id: 'prop-typewriter', name: '打字机', prompt: 'A vintage typewriter with paper, mechanical, game-ready 3D model', category: 'props', height: 0.5 },
  { id: 'prop-gramophone', name: '留声机', prompt: 'A vintage gramophone with brass horn and spinning record, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-telescope-giant', name: '巨型望远镜', prompt: 'A giant astronomical telescope on mount, observatory, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-globe-giant', name: '巨型地球仪', prompt: 'A giant rotating globe on stand, decorative, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-hourglass-giant2', name: '魔法沙漏', prompt: 'A magical hourglass with glowing sand floating, fantasy, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-sundial-giant', name: '巨型日晷', prompt: 'A giant stone sundial in garden, classical, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-fountain-pen', name: '钢笔喷泉', prompt: 'A giant fountain pen sculpture with ink flowing, artistic, game-ready 3D model', category: 'props', height: 4 },
  { id: 'prop-book-giant', name: '巨型书本', prompt: 'A giant open book sculpture with pages turning, library decor, game-ready 3D model', category: 'props', height: 3 },
  { id: 'prop-key-giant', name: '巨型钥匙', prompt: 'A giant ornate golden key sculpture, fantasy, game-ready 3D model', category: 'props', height: 3.5 },
  { id: 'prop-lock-giant', name: '巨型锁', prompt: 'A giant antique padlock sculpture, steampunk, game-ready 3D model', category: 'props', height: 2.5 },
  { id: 'prop-wheel-ship', name: '船舵', prompt: 'A wooden ship wheel decoration, nautical, game-ready 3D model', category: 'props', height: 2 },
  { id: 'prop-barrel-rum', name: '朗姆酒桶', prompt: 'A wooden rum barrel with tap and pirate markings, game-ready 3D model', category: 'props', height: 1.2 },
  { id: 'prop-jolly-roger', name: '海盗旗', prompt: 'A Jolly Roger pirate flag on pole with skull and crossbones, game-ready 3D model', category: 'props', height: 4 },
];

const variants: AssetRequest[] = variantPrompts.map((v, i) =>
  req(v.id, v.category, v.name, v.prompt, 'high', v.height, 100 + i, ['variant']),
);

// ─── Assemble and sort by priority ──────────────────────────────────────────
export const ALL_ASSETS: AssetRequest[] = [
  ...buildings,
  ...cityInfra,
  ...plazaFeatures,
  ...props,
  ...nature,
  ...npcs,
  ...variants,
].sort((a, b) => a.priority - b.priority);

export const ASSET_COUNT = ALL_ASSETS.length;
