// ===== 知识擂台 · 本地兜底题库 =====
// LLM 生成失败时使用；每个领域 ≥15 道硬编码单选题，套路与 DRAFT_FALLBACKS 一致。
import type { QuizDomain, QuizQuestion } from "@balabala/shared";

export const QUIZ_FALLBACK_BANK: Record<QuizDomain, QuizQuestion[]> = {
  // ===== 科学 =====
  science: [
    { prompt: "相对论的主要提出者是？", options: ["牛顿", "爱因斯坦", "伽利略", "普朗克"], correctIndex: 1, explanation: "爱因斯坦1905年提出狭义相对论，1915年完成广义相对论。" },
    { prompt: "万有引力定律是谁提出的？", options: ["牛顿", "爱因斯坦", "霍金", "开普勒"], correctIndex: 0, explanation: "牛顿在《自然哲学的数学原理》中提出万有引力定律。" },
    { prompt: "两获诺贝尔奖、开创放射性研究的是？", options: ["居里夫人", "屠呦呦", "南丁格尔", "林巧稚"], correctIndex: 0, explanation: "居里夫人发现钋和镭，是首位两获诺贝尔奖的女性。" },
    { prompt: "交流电输电系统的主要推动者是？", options: ["爱迪生", "特斯拉", "法拉第", "瓦特"], correctIndex: 1, explanation: "特斯拉推广交流电，与爱迪生的直流电形成电流之战。" },
    { prompt: "图灵机与图灵测试的提出者是？", options: ["冯·诺依曼", "图灵", "香农", "维纳"], correctIndex: 1, explanation: "艾伦·图灵被称为计算机科学与人工智能之父。" },
    { prompt: "DNA 双螺旋结构被发现于哪一年？", options: ["1953", "1903", "1869", "1969"], correctIndex: 0, explanation: "沃森与克里克1953年提出DNA双螺旋结构模型。" },
    { prompt: "光的三原色是？", options: ["红、绿、蓝", "红、黄、蓝", "品红、绿、蓝", "青、黄、品红"], correctIndex: 0, explanation: "色光三原色为红绿蓝，颜料三原色才是红黄蓝。" },
    { prompt: "标准大气压下纯水的沸点约为？", options: ["100℃", "90℃", "110℃", "80℃"], correctIndex: 0, explanation: "海平面标准大气压下纯水沸点为100摄氏度。" },
    { prompt: "提出“日心说”的天文学家是？", options: ["托勒密", "哥白尼", "伽利略", "开普勒"], correctIndex: 1, explanation: "哥白尼在《天体运行论》中提出太阳是宇宙中心。" },
    { prompt: "元素周期表的制定者是？", options: ["门捷列夫", "居里", "拉瓦锡", "道尔顿"], correctIndex: 0, explanation: "俄国化学家门捷列夫1869年发表元素周期表。" },
    { prompt: "生物体结构与功能的基本单位是？", options: ["细胞", "器官", "组织", "蛋白质"], correctIndex: 0, explanation: "细胞学说认为一切生物由细胞构成。" },
    { prompt: "真空中光速约为每秒？", options: ["30万公里", "3万公里", "300万公里", "3000公里"], correctIndex: 0, explanation: "光速约3×10⁸米/秒，即每秒约30万公里。" },
    { prompt: "苹果落地的传说启发了谁思考引力？", options: ["牛顿", "胡克", "哈雷", "玻意耳"], correctIndex: 0, explanation: "牛顿借苹果落地思考引力是否延伸到月球。" },
    { prompt: "量子力学“不确定性原理”的提出者是？", options: ["海森堡", "薛定谔", "玻尔", "普朗克"], correctIndex: 0, explanation: "海森堡1927年提出位置与动量不可同时测准。" },
    { prompt: "蒸汽机的关键改进者是？", options: ["瓦特", "纽科门", "史蒂芬孙", "富尔顿"], correctIndex: 0, explanation: "瓦特改良蒸汽机，直接推动了工业革命。" },
    { prompt: "《物种起源》的作者是？", options: ["达尔文", "华莱士", "赫胥黎", "拉马克"], correctIndex: 0, explanation: "达尔文1859年发表《物种起源》，提出自然选择。" },
    { prompt: "电子这一基本粒子的发现者是？", options: ["汤姆逊", "卢瑟福", "玻尔", "密立根"], correctIndex: 0, explanation: "汤姆逊通过阴极射线实验发现电子。" },
  ],

  // ===== 文学 =====
  literature: [
    { prompt: "《红楼梦》的作者是？", options: ["罗贯中", "曹雪芹", "施耐庵", "蒲松龄"], correctIndex: 1, explanation: "曹雪芹著前八十回，后四十回一般认为由高鹗续写。" },
    { prompt: "“生存还是毁灭，这是一个问题”出自？", options: ["《李尔王》", "《哈姆雷特》", "《麦克白》", "《奥赛罗》"], correctIndex: 1, explanation: "这是《哈姆雷特》著名的独白开篇。" },
    { prompt: "被称为“诗仙”的诗人是？", options: ["杜甫", "李白", "王维", "白居易"], correctIndex: 1, explanation: "李白号青莲居士，浪漫主义诗歌巅峰，世称诗仙。" },
    { prompt: "苏轼的号是？", options: ["青莲居士", "东坡居士", "香山居士", "易安居士"], correctIndex: 1, explanation: "苏轼被贬黄州后开垦东坡，自号东坡居士。" },
    { prompt: "鲁迅的原名是？", options: ["周树人", "周作人", "周建人", "周樟寿后改名周树人"], correctIndex: 0, explanation: "鲁迅原名周树人，周作人是其弟。" },
    { prompt: "《史记》的作者是？", options: ["司马迁", "司马光", "班固", "陈寿"], correctIndex: 0, explanation: "司马迁著中国第一部纪传体通史《史记》。" },
    { prompt: "下列哪部不属于“四书”？", options: ["《大学》", "《中庸》", "《论语》", "《诗经》"], correctIndex: 3, explanation: "四书为大学、中庸、论语、孟子；诗经属五经。" },
    { prompt: "《西游记》的作者是？", options: ["吴承恩", "罗贯中", "施耐庵", "蒲松龄"], correctIndex: 0, explanation: "吴承恩整理创作了神魔小说《西游记》。" },
    { prompt: "“但愿人长久，千里共婵娟”的作者是？", options: ["苏轼", "李白", "杜甫", "辛弃疾"], correctIndex: 0, explanation: "出自苏轼《水调歌头·明月几时有》。" },
    { prompt: "下列哪部不属于莎士比亚“四大悲剧”？", options: ["《哈姆雷特》", "《罗密欧与朱丽叶》", "《李尔王》", "《麦克白》"], correctIndex: 1, explanation: "四大悲剧为哈姆雷特、奥赛罗、李尔王、麦克白。" },
    { prompt: "小说集《呐喊》的作者是？", options: ["鲁迅", "郭沫若", "茅盾", "巴金"], correctIndex: 0, explanation: "《呐喊》收录《狂人日记》《阿Q正传》等。" },
    { prompt: "“落霞与孤鹜齐飞”出自哪篇名文？", options: ["《滕王阁序》", "《岳阳楼记》", "《醉翁亭记》", "《兰亭集序》"], correctIndex: 0, explanation: "王勃《滕王阁序》中的千古名句。" },
    { prompt: "“桃园三结义”不包括下列哪个人？", options: ["刘备", "关羽", "张飞", "赵云"], correctIndex: 3, explanation: "桃园结义为刘备、关羽、张飞三人。" },
    { prompt: "李清照的号是？", options: ["易安居士", "香山居士", "青莲居士", "六一居士"], correctIndex: 0, explanation: "李清照号易安居士，宋代婉约词宗。" },
    { prompt: "“春眠不觉晓，处处闻啼鸟”的作者是？", options: ["孟浩然", "李白", "王维", "杜牧"], correctIndex: 0, explanation: "出自孟浩然《春晓》。" },
    { prompt: "《骆驼祥子》的作者是？", options: ["老舍", "巴金", "茅盾", "曹禺"], correctIndex: 0, explanation: "老舍笔下北平人力车夫祥子的悲剧。" },
    { prompt: "“一千个读者就有一千个哈姆雷特”评价的是？", options: ["莎士比亚", "托尔斯泰", "但丁", "歌德"], correctIndex: 0, explanation: "说明莎剧人物的丰富性与阐释空间。" },
  ],

  // ===== 哲学 =====
  philosophy: [
    { prompt: "“己所不欲，勿施于人”出自？", options: ["孔子", "老子", "墨子", "孙子"], correctIndex: 0, explanation: "出自《论语·卫灵公》，是儒家忠恕之道。" },
    { prompt: "《道德经》的作者是？", options: ["庄子", "老子", "列子", "鬼谷子"], correctIndex: 1, explanation: "老子著《道德经》，道家学派创始人。" },
    { prompt: "“我知道我一无所知”最能代表谁的态度？", options: ["苏格拉底", "柏拉图", "亚里士多德", "泰勒斯"], correctIndex: 0, explanation: "苏格拉底以“自知其无知”开启产婆式追问。" },
    { prompt: "“未经审视的人生不值得过”是谁的名言？", options: ["苏格拉底", "尼采", "康德", "黑格尔"], correctIndex: 0, explanation: "出自柏拉图《申辩篇》中苏格拉底的法庭陈述。" },
    { prompt: "提出“超人”哲学的是？", options: ["叔本华", "尼采", "海德格尔", "萨特"], correctIndex: 1, explanation: "尼采在《查拉图斯特拉如是说》中提出超人。" },
    { prompt: "“道法自然”出自？", options: ["《论语》", "《道德经》", "《庄子》", "《周易》"], correctIndex: 1, explanation: "《道德经》：“人法地，地法天，天法道，道法自然。”" },
    { prompt: "儒家学派的创始人是？", options: ["孔子", "孟子", "荀子", "董仲舒"], correctIndex: 0, explanation: "孔子创立儒家，被尊为万世师表。" },
    { prompt: "“那些杀不死你的，使你更强大”出自？", options: ["尼采", "加缪", "卡夫卡", "叔本华"], correctIndex: 0, explanation: "出自尼采《偶像的黄昏》。" },
    { prompt: "“上善若水”出自？", options: ["老子", "孔子", "墨子", "孙子"], correctIndex: 0, explanation: "《道德经》以水喻柔弱胜刚强。" },
    { prompt: "柏拉图探讨理想城邦的著作是？", options: ["《理想国》", "《形而上学》", "《尼各马可伦理学》", "《对话录》"], correctIndex: 0, explanation: "《理想国》讨论正义、城邦与哲人王。" },
    { prompt: "主张“无为而治”的思想家是？", options: ["老子", "孔子", "韩非", "孙武"], correctIndex: 0, explanation: "道家主张顺应自然、无为而治。" },
    { prompt: "“人是万物的尺度”出自哪位智者？", options: ["普罗泰戈拉", "苏格拉底", "柏拉图", "毕达哥拉斯"], correctIndex: 0, explanation: "古希腊智者普罗泰戈拉的著名命题。" },
    { prompt: "《纯粹理性批判》的作者是？", options: ["康德", "黑格尔", "笛卡尔", "休谟"], correctIndex: 0, explanation: "康德三大批判之首，奠基德国古典哲学。" },
    { prompt: "“我思故我在”是谁的命题？", options: ["笛卡尔", "培根", "莱布尼茨", "斯宾诺莎"], correctIndex: 0, explanation: "笛卡尔通过普遍怀疑确立“我思”。" },
    { prompt: "被尊为儒家“亚圣”的是？", options: ["孟子", "孔子", "曾子", "荀子"], correctIndex: 0, explanation: "孟子继承孔子，主张性善论与仁政。" },
    { prompt: "下列哪篇是庄子的代表作？", options: ["《逍遥游》", "《兼爱》", "《非攻》", "《五蠹》"], correctIndex: 0, explanation: "《逍遥游》展现庄子绝对自由的精神境界。" },
    { prompt: "“存在即被感知”属于哪位哲学家？", options: ["贝克莱", "洛克", "休谟", "笛卡尔"], correctIndex: 0, explanation: "贝克莱主观唯心主义的著名命题。" },
  ],

  // ===== 历史 =====
  history: [
    { prompt: "赤壁之战中孙刘联军的主要对手是？", options: ["曹操", "袁绍", "董卓", "吕布"], correctIndex: 0, explanation: "208年赤壁之战，孙刘联军大破曹操。" },
    { prompt: "秦始皇统一六国完成于哪一年？", options: ["公元前221年", "公元前202年", "公元220年", "公元前475年"], correctIndex: 0, explanation: "公元前221年秦灭齐，完成统一。" },
    { prompt: "“贞观之治”是哪位皇帝在位时期？", options: ["唐太宗", "唐玄宗", "汉高祖", "宋太祖"], correctIndex: 0, explanation: "唐太宗李世民年号贞观，开创盛世。" },
    { prompt: "西汉出使西域、开辟丝绸之路的是？", options: ["张骞", "苏武", "班超", "玄奘"], correctIndex: 0, explanation: "张骞两次出使西域，打通丝绸之路。" },
    { prompt: "刘备“三顾茅庐”请出的是？", options: ["诸葛亮", "庞统", "司马懿", "周瑜"], correctIndex: 0, explanation: "诸葛亮隐居隆中，刘备三顾请其出山。" },
    { prompt: "北宋的建立者是？", options: ["赵匡胤", "赵构", "赵光义", "赵普"], correctIndex: 0, explanation: "赵匡胤陈桥兵变，建立宋朝。" },
    { prompt: "“焚书坑儒”发生在哪位皇帝在位时？", options: ["秦始皇", "汉武帝", "汉高祖", "隋炀帝"], correctIndex: 0, explanation: "秦始皇为加强思想控制而焚书坑儒。" },
    { prompt: "唐朝鼎盛时期的都城是？", options: ["长安", "洛阳", "建康", "开封"], correctIndex: 0, explanation: "长安即今日西安，是唐帝国都城。" },
    { prompt: "郑和下西洋发生在哪个朝代？", options: ["明朝", "宋朝", "清朝", "元朝"], correctIndex: 0, explanation: "明成祖派郑和七下西洋。" },
    { prompt: "“挟天子以令诸侯”的是？", options: ["曹操", "袁绍", "董卓", "刘备"], correctIndex: 0, explanation: "曹操迎汉献帝于许，借朝廷名义号令各方。" },
    { prompt: "辛亥革命爆发于哪一年？", options: ["1911", "1919", "1898", "1921"], correctIndex: 0, explanation: "1911年武昌起义，史称辛亥革命。" },
    { prompt: "中国历史上第一个统一的中央集权王朝是？", options: ["秦朝", "夏朝", "汉朝", "周朝"], correctIndex: 0, explanation: "公元前221年秦朝建立，首创郡县制。" },
    { prompt: "“卧薪尝胆”说的是哪位君主？", options: ["越王勾践", "吴王夫差", "秦始皇", "刘邦"], correctIndex: 0, explanation: "勾践忍辱负重，终灭吴复仇。" },
    { prompt: "指南针开始广泛应用于航海是在？", options: ["宋代", "唐代", "汉代", "明代"], correctIndex: 0, explanation: "宋代航海已普遍使用罗盘指南针。" },
    { prompt: "改进造纸术的东汉人物是？", options: ["蔡伦", "张衡", "毕昇", "华佗"], correctIndex: 0, explanation: "蔡伦改进造纸术，人称蔡侯纸。" },
    { prompt: "“文景之治”出现在哪个朝代？", options: ["西汉", "东汉", "唐朝", "宋朝"], correctIndex: 0, explanation: "汉文帝、汉景帝时期休养生息，史称文景之治。" },
    { prompt: "科举制度正式确立于哪个朝代？", options: ["隋朝", "汉朝", "唐朝", "宋朝"], correctIndex: 0, explanation: "隋炀帝设进士科，科举制正式形成。" },
  ],

  // ===== 艺术 =====
  art: [
    { prompt: "《蒙娜丽莎》的作者是？", options: ["达·芬奇", "米开朗基罗", "拉斐尔", "梵高"], correctIndex: 0, explanation: "达·芬奇的肖像名作，藏于卢浮宫。" },
    { prompt: "《星月夜》的作者是？", options: ["梵高", "莫奈", "塞尚", "高更"], correctIndex: 0, explanation: "梵高后印象派代表作，旋转的星空。" },
    { prompt: "《最后的晚餐》的作者是？", options: ["达·芬奇", "伦勃朗", "米开朗基罗", "拉斐尔"], correctIndex: 0, explanation: "达·芬奇绘于米兰圣玛利亚感恩教堂。" },
    { prompt: "《向日葵》系列的作者是？", options: ["梵高", "莫奈", "毕加索", "马蒂斯"], correctIndex: 0, explanation: "梵高在阿尔勒画下多幅向日葵。" },
    { prompt: "文艺复兴“美术三杰”不包括？", options: ["但丁", "达·芬奇", "米开朗基罗", "拉斐尔"], correctIndex: 0, explanation: "三杰为达芬奇、米开朗基罗、拉斐尔；但丁是文学三杰。" },
    { prompt: "雕塑《思想者》的作者是？", options: ["罗丹", "米开朗基罗", "贝尼尼", "多纳泰罗"], correctIndex: 0, explanation: "罗丹《地狱之门》组雕中的著名形象。" },
    { prompt: "印象派因哪幅画而得名？", options: ["《日出·印象》", "《睡莲》", "《干草堆》", "《奥林匹亚》"], correctIndex: 0, explanation: "莫奈《日出·印象》被批评家讥讽，印象派由此得名。" },
    { prompt: "《日出·印象》的作者是？", options: ["莫奈", "马奈", "雷诺阿", "德加"], correctIndex: 0, explanation: "莫奈是印象派代表人物。" },
    { prompt: "《格尔尼卡》的作者是？", options: ["毕加索", "达利", "马蒂斯", "米罗"], correctIndex: 0, explanation: "毕加索为抗议格尔尼卡轰炸而作。" },
    { prompt: "被尊为“书圣”的书法家是？", options: ["王羲之", "颜真卿", "张旭", "柳公权"], correctIndex: 0, explanation: "王羲之《兰亭集序》被誉为天下第一行书。" },
    { prompt: "《清明上河图》的作者是？", options: ["张择端", "顾恺之", "吴道子", "唐寅"], correctIndex: 0, explanation: "北宋张择端描绘汴京清明时节。" },
    { prompt: "贝多芬是哪国作曲家？", options: ["德国", "奥地利", "波兰", "法国"], correctIndex: 0, explanation: "贝多芬生于德国波恩，后定居维也纳。" },
    { prompt: "《星月夜》属于哪个绘画流派？", options: ["后印象派", "印象派", "立体派", "抽象派"], correctIndex: 0, explanation: "梵高是后印象派代表，强调主观色彩。" },
    { prompt: "达·芬奇是哪国人？", options: ["意大利", "法国", "西班牙", "荷兰"], correctIndex: 0, explanation: "达·芬奇生于意大利芬奇镇。" },
    { prompt: "大理石雕塑《大卫》的作者是？", options: ["米开朗基罗", "罗丹", "贝尼尼", "多纳泰罗"], correctIndex: 0, explanation: "米开朗基罗26岁完成的《大卫》。" },
    { prompt: "被尊为“画圣”的唐代画家是？", options: ["吴道子", "顾恺之", "阎立本", "张择端"], correctIndex: 0, explanation: "吴道子善画佛道人物，尊为画圣。" },
    { prompt: "梵高的国籍是？", options: ["荷兰", "法国", "西班牙", "意大利"], correctIndex: 0, explanation: "梵高生于荷兰，后在法国创作。" },
  ],
};
